version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./packages/database/conf:/etc/mongo
      - mongodb_data:/data/db
    networks:
      - backend
    ports:
      - 8080:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
  mongo_admin:
    image: mongo-express:latest
    restart: always
    networks:
      - backend
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_URL: "mongodb://root:password@mongo:27017/"
